#+Title: Damagebdd - Accounts

#+INCLUDE: "header.org"

** Create an Account

To fully utilize the capabilities of DamageBDD, you need to create and fund an account.

To create an account, you must first have a `Refund Address`, which is
the address where unused bitcoin can be refunded back to you. It is
important to ensure that you have control over this address.

Use the following forms to create an account:


- [[/register-individual.html][Individual Registration Form]]
- [[/register-business.html][Business Registration Form]]


After submitting the form, you will receive a confirmation link in
your email. Click on the link and set a password for your account.

Once you have set a password, you can check your account balance and
bitcoin payment address using the following command:

#+BEGIN_EXPORT html
<pre>
<code class="language-shell">
    curl https://run.damagebdd.com/accounts/balance?account=xxx
</code>
</pre>
#+END_EXPORT

where `xxx` is replaced with the account id (provided in confirmation email)

To use the premium features top up the bitcoin address with some sats
and they will be used to fund the execution of the test and support
the development of the product.

*** Pricing

Please refer to [[./pricing.html][pricing page]] for pricing.

*** Refunds

To understand bitcoin refunds better please refer bitcoin guide on [[https://developer.bitcoin.org/devguide/payment_processing.html#issuing-refunds][issuing refund]].

To review DamageBDD's pricing and execution [[https://github.com/jagguli/DamageBDD/tree/master/contracts][contracts]].

** Issuing a refund

Withdrawing unused funds back into the refund address is easy.

#+BEGIN_EXPORT html
<pre>
<code class="language-shell">
    curl -s 'https://run.damagebdd.com/accounts/refund?account=$CONTRACT_ADDRESS' |jq
</code>
</pre>
#+END_EXPORT
