#+TITLE: Pricing - DamageBDD

#+INCLUDE: "header.org"

* Pricing Plans for DamageBDD


We calculate pricing based on the number of steps and their
implementations. Each step is individually priced based on the
resources used and complexity involved. If you run steps concurrently,
each execution will count against the total number of step
executions. For example, running one step 10 times will deduct 10
Damage Tokens from your balance.

Please note that pricing may be subject to change as we continue to
update and improve our product. We recommend checking this page
regularly for any updates.

** Step Based Pricing

Here is a breakdown of our step-based pricing:

1 Damage Token = 100 Satoshis (0.000001 BTC) per token.

| Step          | Price in Sats |
|---------------|---------------|
| Simple Step   | 1 DAMAGE      |
| Selenium Step | 500 DAMAGE    |
| Appium Step   | 1000 DAMAGE   |


We hope this pricing information is clear and easy to understand. If
you have any further questions or need assistance, please don't
hesitate to contact our support team.

** Consultation Pricing

If you're looking to quickly integrate DamageBDD into your team's
workflow, book a consultation with DamageBDD's experts.

#+BEGIN_EXPORT html
<a href="https://calendly.com/melit-stevenjoseph/15min">Schedule a Call with DamageBDD Now</a>
#+END_EXPORT
