#+TITLE: Pricing - DamageBDD

#+INCLUDE: "header.org"
* Pricing Plans for damageBDD.com

DamageBDD is a registered business entity in Australia, holding an
Australian Business Number (ABN) . 


#+BEGIN_EXPORT html

<div style="border: 1px solid #333; padding: 10px; margin: 10px 0; background-color: #f9f9f9;">
  <strong>
  Test it out on the bitcoin testnet!
</strong>
<br>
 Damagebdd is currently available for testing all features on the testnet.
 Simply register to receive a bitcoin testnet payment address.
 Test bitcoins can be the sent to the payment address from a faucet like <a href="https://testnet-faucet.com/">this</a>.
</div>
#+END_EXPORT
 

* Accepted Payment Methods

- Accepts payments in Bitcoin (BTC)

* Payment plans

DamageBDD uses Bitcoin for account payments.

Use the bitcoin address sent to your account email to send some bitcoin to fund execution of tests and to use paid features of DamageBDD.

Since DamageBDD runs on a pay as you go model, simply send any amount that will be sufficient to run your tests, but take into consdideration that smaller tha.

DamageBdd's pricing is per step and step implementation based.

Which means each step is priced according to the usage of resources
and complexity.

Running steps concurrently will count against each step excution, ie

running 1 step 10 times will deduct 10 Units.

Pricing is subject to change as the product features evolve, please refer back to this page for updates.

** Step Based Pricing


| Step           | Price in Sats                       |
|----------------|------------------------------------:|
| Simple Step    | 1 Sat per 100,000  Step executions  |
| Selenium Step  | 1 Sat per 50,000 Step executions    |
| Appium Step    | 1 Sat per 1000 Step executions      |


** Create an account to start using paid features

Creating an account to start using paid features is easy.

To create an account you must first have a `Refund Address`.

The `Refund Address` is where unused bitcoin can be refunded back to you.

Make sure you have control over the `Refund Address`.

Once you have a refund address simply call the `accounts/create` endpoint.


[[./register-individual.html][Individual Registration Form]]

or


[[./register-business.html][Business Registration Form]]

To understand bitcoin refunds better please refer bitcoin guide on [[https://developer.bitcoin.org/devguide/payment_processing.html#issuing-refunds][issuing refund]].

To review DamageBDD's pricing and execution [[https://github.com/jagguli/DamageBDD/tree/master/contracts][contracts]].

** Issuing a refund

Withdrawing unused funds back into the refund address is easy.

#+BEGIN_EXPORT html
<pre>
<code class="language-shell">
    curl -s 'https://run.damagebdd.com/accounts/refund?account=$CONTRACT_ADDRESS' |jq
</code>
</pre>
#+END_EXPORT

** Consultation Pricing

Easiest way to get started with DamageBDD in your team's work flow quickly, book a consultation with DamageBDD. 

#+BEGIN_EXPORT html
<a href="https://calendly.com/melit-stevenjoseph/15min">Schedule Call with DamageBDD Now</a>
#+END_EXPORT
