#+TITLE: Pricing - DamageBDD

#+INCLUDE: "header.org"

* Pricing Plans for DamageBDD

At DamageBDD, we offer affordable pricing options for you to pay using
the Bitcoin Lightning Network. With our easy-to-use platform, you can
sign up for an [[./accounts.org][account]] and generate a Lightning Invoice for any
amount. This payment will fund the execution of your tests and provide
access to our premium features and paid support.

To access the premium features of DamageBDD, please start by creating
an [[./accounts.org][Account]]. Upon signup, you will be given a certain amount of free
credits. Once you have exhausted the free credits, you can easily
obtain more credits by making a lightning payment.

Our pricing model is designed to be flexible and convenient for our
users. With DamageBDD, you only pay for what you use, thanks to our
pay-as-you-go pricing. This means that you can simply send any amount
of bitcoin that will be sufficient to run your tests. However, please
keep in mind the resources and complexity involved in your tests when
determining the amount to send.

We calculate pricing based on the number of steps and their
implementations. Each step is individually priced based on the
resources used and complexity involved. If you run steps concurrently,
each execution will count against the total number of step
executions. For example, running one step 10 times will deduct 10
Damage Tokens from your balance.

Please note that pricing may be subject to change as we continue to
update and improve our product. We recommend checking this page
regularly for any updates.

** Step Based Pricing

Here is a breakdown of our step-based pricing in Satoshis (sats) per
step execution:

| Step          | Price in Sats                   |
|---------------|--------------------------------:|
| Simple Step   | 1 Sat per 100,000 Step executions |
| Selenium Step | 1 Sat per 50,000 Step executions   |
| Appium Step   | 1 Sat per 1,000 Step executions    |

We hope this pricing information is clear and easy to understand. If
you have any further questions or need assistance, please don't
hesitate to contact our support team.

** Consultation Pricing

If you're looking to quickly integrate DamageBDD into your team's
workflow, book a consultation with DamageBDD's experts.

#+BEGIN_EXPORT html
<a href="https://calendly.com/melit-stevenjoseph/15min">Schedule a Call with DamageBDD Now</a>
#+END_EXPORT
